version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 6543:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: admin

volumes:
  postgres_data: